### ISSUE TITLE
[PUB-22] Support generated backend addresses in any build

### ISSUE THREAD

**Issue by hugosantos** [namespacelabs/foundation#1014]
At the moment this support is only available under the "web" integration.

Ideally we'd have the "emit backend address" code available as a codegen rule that can be used in other builds. Although probably this would be limited to buildkit builds so that the input can be dynamically generated.

The web integration always emits a json file. One thing to figure out is whether that's enough, or we should instead model the backend addresses as a resource, which would be injectable into an invocation, and the invocation would then produce the output that would be codegen'd.

The non-simple syntax would be something like:

```
server: {
  build: {
    generate: {
      "path/to/output": {
        binary: "path/to/generator"
        resources: {
          backendconfig: {
            class: "namespacelabs.dev/foundation/library/runtime:IngressConfiguration"
            input: "server/package"
          }
        }
      }
    }
  }
}
```

<sub>[PUB-22](https://linear.app/namespacelabs/issue/PUB-22/support-generated-backend-addresses-in-any-build)</sub>

**Comment by hugosantos** [comment]
Requested by @szferi fyi @nicolasalt

**Comment by nicolasalt** [comment]
I'm thinking that we probably don't need this multi-layer indirection at the moment. In my understanding, from the user perspective the syntax should be similar to `fromServiceEndpoint`, for example, `fromServiceIngress`:

```
env: {
	INGRESS: fromServiceIngress: "github.com/user/repo/myserver:webapi"
}
```

The injected address will be available publicly available for remote k8s clusters and available locally on the user machine for the local cluster, the same way Web `backends` work now.

**Comment by hugosantos** [comment]
@nicolasalt that may solve the one need, lets open a separate bug to what you're proposing. And lets leave this open for the more general purpose codegen use which has other uses.

**Comment by nicolasalt** [comment]
Filed #1019
