### ISSUE TITLE
[PUB-17] Allow Resource Classes to operate as providers

### ISSUE THREAD

**Issue by hugosantos** [namespacelabs/foundation#1016]
At the moment, the resource class and provider separation is strict. We've since observed resources which have a 1-to-1 map between class and provider; i.e. types that represent semantics of a particular provider, and whose class will never be used by different providers.

https://github.com/namespacelabs/foundation/blob/819a3f5432962951fcfb4e523be56dbf1d3538c1/library/kubernetes/rbac/resourceclasses.cue is an example; and it works around this limitation by defining a `defaultProvider`. This enables the resource to be inlinable, like e.g. https://github.com/namespacelabs/foundation/blob/819a3f5432962951fcfb4e523be56dbf1d3538c1/library/oss/externaldns/resources.cue#L2-L5 but it's still a maintenance and discoverability problem.

This change would collapse some of the provider behavior into resource classes, i.e. `initializedWith`, `prepareWith`, etc. The ability to use a separate provider would be maintained, but wouldn't be the default anymore.

<sub>[PUB-17](https://linear.app/namespacelabs/issue/PUB-17/allow-resource-classes-to-operate-as-providers)</sub>

**Comment by hugosantos** [comment]
FYI @nicolasalt

**Comment by nicolasalt** [comment]
Do you mean essentially allowing to inline the default provider definition? E.g. instead of

```
defaultProvider: "namespacelabs.dev/foundation/library/cloudflare/tunnel"
```

it would be

```
defaultProvider: {
  initializedWith: {...}
  ...
}
```

**Comment by hugosantos** [comment]
Inline the provider, yes. But the idea that there's a default is part of what I'm contesting here. It feels to me that we'll see more of the pattern of a class that really only has one provider. `defaultProvider` would seem to indicate that it can still be changed, and I'm not sure that makes much sense.

What I'm converging on is that a resource user defines the intended instance type (T) and instance name (N), and then the "class" / "provider" (which may need a new name -- perhaps "constructor") is a function of the type `Intent -> T`.

And then having multiple providers fulfill the same class becomes type checking on the instance type alone.
