### ISSUE TITLE
[PUB-18] Explore having the option of defining resource types inline, using cue constraints

### ISSUE THREAD

**Issue by hugosantos** [namespacelabs/foundation#1017]
Instead of:

```
resourceClasses: {
	"Database": {
		description: "Postgres Database"
		intent: {
			type:   "library.database.postgres.DatabaseIntent"
			source: "./database.proto"
		}
	}
```

Support something like:
```
resourceClasses: {
	"Database": {
		description: "Postgres Database"
		intent: {
                         name:   string
                         schema: [...foundation.FileContents]
		}
	}
```

<sub>[PUB-18](https://linear.app/namespacelabs/issue/PUB-18/explore-having-the-option-of-defining-resource-types-inline-using-cue)</sub>

**Comment by hugosantos** [comment]
@szferi thoughts?

**Comment by n-g** [comment]
Personally, I like that I can use proto gen code to parse intents when implementing a provider.
So being able to define an intent in CUE would simplify the definition process, but complicate the implementation for me.

Another note: I believe that supporting both syntaxes simultaneously would easily become messy (what if I want to name my field `source`)

So I am inclined to stay with the current syntax, but I am also a big proto fan in general, so there's a strong bias here 😄
