### ISSUE TITLE
[PUB-20] Move `resource` inputs to the intent

### ISSUE THREAD

**Issue by hugosantos** [namespacelabs/foundation#1018]
`resource` was added separately to get us bootstrapped, but we should now be able to collapse both definitions.

```
message DatabaseIntent {
    string   name                                  = 1;
    repeated foundation.schema.FileContents schema = 2;
    // The following would be added:
    ClusterInstance cluster = 3;
}
```

Instead of:
```
		inputs: {
			cluster: "namespacelabs.dev/foundation/library/database/postgres:Cluster"
		}
```

And it would be specified as:

```
resources: {
  foobar: {
    class: "namespacelabs.dev/foundation/library/database/postgres:Database"
    intent: {
      name: "foobar"
      schema: ["foobar.sql"]
      cluster: "namespacelabs.dev/foundation/library/oss/postgres:colocated"
    }
  }
}
```

<sub>[PUB-20](https://linear.app/namespacelabs/issue/PUB-20/move-resource-inputs-to-the-intent)</sub>

**Comment by n-g** [comment]
We could migrate existing uses to use package refs in the intent 
https://github.com/namespacelabs/foundation/blob/de48eb4e22dcc9394dec8dc42a9c5b74eb02e4c0/library/oss/postgres/types.proto#L16-L17
https://github.com/namespacelabs/foundation/blob/de48eb4e22dcc9394dec8dc42a9c5b74eb02e4c0/library/oss/postgres/prepare/clusterinstance/main.go#L34-L35

and then mark `resource inputs` as deprecated.
