### ISSUE TITLE
[PUB-41] exploration: alternative syntax to declare resources

### ISSUE THREAD

**Issue by hugosantos** [namespacelabs/foundation#1025]
Considering a more compact syntax for resources. With https://github.com/namespacelabs/foundation/issues/1016, most of the times we would be specifying the constructor.

Options:

(1) Special-casing the constructor definition using `$class`, or perhaps `$constructor`.
```
resources: {
  database: {
    $class: "namespacelabs.dev/foundation/library/database/postgres:Database"

    name: "todos"
    schema: ["schema.sql"]
  }
}
```

(2) Using the constructor reference as a single-key map, as we do for volumes:

```
resources: {
  database: "namespacelabs.dev/foundation/library/database/postgres:Database": {
    name: "todos"
    schema: ["schema.sql"]
  }
}
```

(3) A variant of (1), use generated CUE templates:

```
import "namespacelabs.dev/foundation/library/database/postgres"

// This package would include (which would be automatically generated by ns):
// resourceClasses: Database: {
//   $class: "namespacelabs.dev/foundation/library/database/postgres"
//   ...
// }

resources: database: postgres.resourceClasses.Database & {
  name: "todos"
  schema: ["schema.sql"]
}

```

(4) A variant of (3), using CUE function declaration, which will come soon to CUE:

```
import "namespacelabs.dev/foundation/library/database/postgres"

resources: database: postgres.resourceClasses.Database(name: "todos", schema: ["schema.sql"])
```

This would replace:
```
	resources: {
		todosDatabase: {
			class:    "namespacelabs.dev/foundation/library/database/postgres:Database"

			intent: {
				name: "todos"
				schema: ["schema.sql"]
			}
		}
	}
```

<sub>[PUB-41](https://linear.app/namespacelabs/issue/PUB-41/exploration-alternative-syntax-to-declare-resources)</sub>

**Comment by gmichelo** [comment]
I like option 4, which feels like IaC. If function declarations are not yet supported by CUE, then I would go for option 3. Transitioning from option 3 to 4 looks natural to me.

Question: why do we need `resourceClasses` in the below package? Can it be `Database` directly so that the usage would be shorter: `postgres.Database`?

```
// This package would include (which would be automatically generated by ns):
// resourceClasses: Database: {
//   $class: "namespacelabs.dev/foundation/library/database/postgres"
//   ...
// }
```

If that isn't possible, I wonder if we could shorten the string `resourceClasses` into `classes` or similar.
