### ISSUE TITLE
[PUB-24] Service endpoint cannot referenced in co-dependent services

### ISSUE THREAD

**Issue by szferi** [namespacelabs/foundation#1052]
If there is a server that requires a worker, but the worker needs the environment variable like:

```
envs: {
     COMPASS_BASE_ENDPOINT: fromServiceEndpoint: "server:api"
}
```

Then we get the following error by `ns dev`

```
"server" is referenced in "fromServiceEndpoint" but it is not in the server stack. Please explitly add this server to the `requires` list.
```

But specifying the server as required in the worker leads to circular references, and `ns dev` goes into deadlock.
(never mind the typo in the error message)

<sub>[PUB-24](https://linear.app/namespacelabs/issue/PUB-24/service-endpoint-cannot-referenced-in-co-dependent-services)</sub>

**Comment by hugosantos** [comment]
So this is for a situation where: server depends on worker, and worker depends on server, is that right?

We don't support cyclic dependencies -- maybe yet. :-)

**Comment by szferi** [comment]
Yes, indeed it is cyclic dependence from an abstract point of view. However, it would be good to have a way where I can relay on, for example, the DNS-based service discovery that K8S provides in some way.
