### ISSUE TITLE
`ns dev` eats memory if large file exists in the workspace even if it is ignored by `.dockerignore`

### ISSUE THREAD

**Issue by szferi** [namespacelabs/foundation#1054]

**Comment by hugosantos** [comment]
@szferi I guess this is is still an issue, but double-checking.

**Comment by szferi** [comment]
Yes

**Comment by n-g** [comment]
@szferi Does the error persist with the newest release?

I expect that https://github.com/namespacelabs/foundation/commit/18beb0732de5d8fa32e994c23309520f051545ec fixed it.

**Comment by szferi** [comment]
Yes, if, for example, there is a sizeable python virtual env directory in the source and I forgot to put it into a .dockerignore, then an `fs.snapshot` reads it and runs out of memory.

**Comment by n-g** [comment]
Thanks for checking again!

The bug title reads `even if it is ignored by .dockerignore`, so I was only considering the case of large files that are already marked to be ignored.
In your example, why would you expect `ns` to ignore the large file?
Is it implicit as the instructions from your `Dockerfile` don't touch that file?

In that case, we'd need a smarter Dockerfile integration that understands which files are required for the snapshot.
Is managing `.dockerignore` a large burden for you right now?

**Comment by szferi** [comment]
You are right. This issue can be closed because, indeed, if it is ignored that it works.
However, it is worth opening another for cases when there are a lot of files (not necessarily large in size cca 400MB) in a sub dir (like .venv). It is not ignored, but NS still crashes. I know there is a check for this, but it is not always triggered.
