### ISSUE TITLE
[PUB-45] `ns prepare gke` silently fail to create repo at artifact registry

### ISSUE THREAD

**Issue by szferi** [namespacelabs/foundation#1057]
If the user has no artifact registry enabled, then `ns prepare gke` runs successfully, but the `ns deploy` fails.

<sub>[PUB-45](https://linear.app/namespacelabs/issue/PUB-45/ns-prepare-gke-silently-fail-to-create-repo-at-artifact-registry)</sub>

**Comment by hugosantos** [comment]
Do you mean if the "Artifact Registry" API is not enabled?

**Comment by szferi** [comment]
Yes.
