### ISSUE TITLE
On GKE cluster orchestrator wait for nginx ingress controller even if the cluster was prepared with gclb

### ISSUE THREAD

**Issue by szferi** [namespacelabs/foundation#1064]
After `ns prepare gke --env=prod --experimental_use_gclb ...` 
if I try to deploy with `ns deploy --env=prod ./infra/server` where the server has ingress configured with proper domains
then the deployment deadlock in the following message:
`Waiting until Ingress controller is ready`

However, since the GCLB Waiter returns null, this message should not be seen unless the orchestrator waits for nginx ingress controller instead.

If I run the `ns deploy` with `--use_orchestrator=false`, the deployment works properly.

**Comment by n-g** [comment]
I released a  new cli version `v0.0.142` and a new orchestrator with https://github.com/namespacelabs/foundation/commit/2084e5e0cb55243d1b252b449a739667b982b9d3

Please let me know if the issue persists :)

**Comment by szferi** [comment]
It is fixed with `v0.0.158`
