### ISSUE TITLE
[PUB-26] Enable constraining deploy/dev to a single server

### ISSUE THREAD

**Issue by hugosantos** [namespacelabs/foundation#1076]
We always analyze + build + deploy the dependency tree defined by whatever root the user starts with. But sometimes users don't want to touch dependencies, and only update the focused server.

This could be a new flag to `deploy`: `--server-only` or `--focus-only`.

<sub>[PUB-26](https://linear.app/namespacelabs/issue/PUB-26/enable-constraining-deploydev-to-a-single-server)</sub>

**Comment by ADustyOldMuffin** [comment]
Would it also be possible to pass in say a specific server I wish to update? IE in relation to #1075 I don't have a normal "root" and but I want to update a component of the stack.
