### ISSUE TITLE
`ns dev` hangs with slient error at `fs.snapshot`

### ISSUE THREAD

**Issue by szferi** [namespacelabs/foundation#1125]
If you have, for example, a broken symlink in the workspace, even if it is ignored by `.dockerignore`, ns hangs. Only with `--debug_to_console` you can find an error like this:

```
Feb 21 15:45:07.824 UTC fs.snapshot err=open bar: no such file or directory waited=135us took=129us
```

This error never surfaces for the user.

**Comment by n-g** [comment]
https://github.com/namespacelabs/foundation/commit/deb2d69a0a4c87c8e709454443e00c482367c8c3 ensures that the error surfaces to the caller.
Looking into our handling of `.dockerignore` next.
