### ISSUE TITLE
[PUB-4] You are only permitted to remove 100 repositories at a time.  

### ISSUE THREAD

**Issue by ghuntley** [namespacelabs/foundation#1186]
Scenario:
- I originally added GitHub user `ghuntley` with read/write to all for GitHub Actions Runners under this account.
- I wish to reduce scope to just `ghuntley/ghuntley` and when doing so below happens.

<img width="996" alt="CleanShot 2023-06-06 at 14 44 17@2x" src="https://github.com/namespacelabs/foundation/assets/127353/9e933949-cae1-48a0-990d-2059a674bf58">

<img width="1007" alt="CleanShot 2023-06-06 at 14 43 01@2x" src="https://github.com/namespacelabs/foundation/assets/127353/c7b9a9a6-9452-49e5-b33e-6713cba90990">

<sub>[PUB-4](https://linear.app/namespacelabs/issue/PUB-4/you-are-only-permitted-to-remove-100-repositories-at-a-time)</sub>

**Comment by hugosantos** [comment]
This seems like a GitHub limitation @ghuntley; we defer to GitHub on this as they do the access control. I'm closing this as working-as-intended even though it sucks. I suggest removing the application, and constrain it to the set of repos you want on reinstallation.
