### ISSUE TITLE
[PUB-3] Cluster is created but "No clusters" reported in CONTINUOUS INTEGRATION section

### ISSUE THREAD

**Issue by ghuntley** [namespacelabs/foundation#1187]
![CleanShot 2023-06-06 at 14 46 34](https://github.com/namespacelabs/foundation/assets/127353/f87db1b9-1e9b-4c13-b543-115565cb7a49)

<sub>[PUB-3](https://linear.app/namespacelabs/issue/PUB-3/cluster-is-created-but-no-clusters-reported-in-continuous-integration)</sub>

**Comment by hugosantos** [comment]
Yeap, this is not great. The CI view should be focused on setting up Managed Runners; the empty state that leads to "Create cluster" is not well placed there.

**Comment by hugosantos** [comment]
An update on this: we're working on a GH-focused view that will replace the current cluster list. Coming soon!

**Comment by hugosantos** [comment]
We've just released a new GitHub runner focused view which also addresses the empty state problem you've identified. Give it a try and let us know!

<img width="1357" alt="Screenshot_2023-06-09_at_12 33 38" src="https://github.com/namespacelabs/foundation/assets/175449/1a7c95d2-41e8-4221-8b8c-ff381ba766ea">
