### ISSUE TITLE
[PUB-2] [GitHub actions] $USER must be set. If running in a container, try setting USER=root.::error::Action 

### ISSUE THREAD

**Issue by ghuntley** [namespacelabs/foundation#1188]
See failing build at https://github.com/ghuntley/ghuntley/actions/runs/5184733416/jobs/9343922585

<img width="1665" alt="CleanShot 2023-06-06 at 14 58 28@2x" src="https://github.com/namespacelabs/foundation/assets/127353/30ea4873-13b4-4e9d-b1a3-d892dce61d65">

After adopting namespace.so for builds via this commit at https://github.com/ghuntley/ghuntley/commit/0f33f9a1094ec5e2cd4ff01812e0f019ac02bd39

<img width="870" alt="CleanShot 2023-06-06 at 14 58 06@2x" src="https://github.com/namespacelabs/foundation/assets/127353/8f4965d4-d4a5-4dac-8409-f9b541c23682">

This workflow works correctly when using GitHub's `runs-on: ubuntu-latest`

See build run of commit before this one at https://github.com/ghuntley/ghuntley/actions/runs/5096692870/jobs/9162736718

<img width="1672" alt="CleanShot 2023-06-06 at 14 58 50@2x" src="https://github.com/namespacelabs/foundation/assets/127353/8d418d56-9e60-4b48-a8e7-75eb27b72184">

<sub>[PUB-2](https://linear.app/namespacelabs/issue/PUB-2/[github-actions]-dollaruser-must-be-set-if-running-in-a-container-try)</sub>

**Comment by edganiukov** [comment]
Hi @ghuntley
Thanks for reporting!
I've fixed the issue - namespace manage runners now have `USER` env variable set.

**Comment by ghuntley** [comment]
Can confirm that this particular has been resolved and am now able to progress further with building my monorepo on namespace.
