### ISSUE TITLE
[PUB-1] community.namespace.so: The initial connection between Cloudflare's network and the origin web server timed out. 

### ISSUE THREAD

**Issue by ghuntley** [namespacelabs/foundation#1191]
Following link in `ns` (installed via homebrew)
 
<img width="1447" alt="CleanShot 2023-06-06 at 15 27 32@2x" src="https://github.com/namespacelabs/foundation/assets/127353/a352b7bb-3875-4ffb-b1c1-344ffd75dd5d">

<img width="1515" alt="CleanShot 2023-06-06 at 15 27 15@2x" src="https://github.com/namespacelabs/foundation/assets/127353/f50b0b8c-6e53-47f2-bb15-e942e8abf051">

<sub>[PUB-1](https://linear.app/namespacelabs/issue/PUB-1/communitynamespaceso-the-initial-connection-between-cloudflares)</sub>

**Comment by hugosantos** [comment]
If I visit [https://community.namespace.so/discord/](https://community.namespace.so/discord/) I see the same message; checking

**Comment by hugosantos** [comment]
I've fixed the 302 for `/discord/`(note forward slash); but this is a bit too complicated on our side. Filed [NSL-1166](https://linear.app/namespacelabs/issue/NSL-1166/move-discord-redirect-to-just-be-a-sub-path-of-namespaceso) for a follow up.
