### ISSUE TITLE
[PUB-8] cachix: mmap 4096 bytes at (nil): Cannot allocate memory

### ISSUE THREAD

**Issue by ghuntley** [namespacelabs/foundation#1192]
This job at https://github.com/ghuntley/ghuntley/actions/runs/5184733416/jobs/9349809411#step:4:18 works 👍 on GitHub hosted runners but on Namespace it is ⚔️ 

<img width="1628" alt="CleanShot 2023-06-06 at 20 27 19@2x" src="https://github.com/namespacelabs/foundation/assets/127353/7a19c944-0e6f-4a4f-8202-f6aaf1147fa0">

<sub>[PUB-8](https://linear.app/namespacelabs/issue/PUB-8/cachix-mmap-4096-bytes-at-nil-cannot-allocate-memory)</sub>

**Comment by gmichelo** [comment]
Thanks @ghuntley for the above steps! We are setting them up internally to reproduce the issue and fix it.

**Comment by gmichelo** [comment]
We have tested the fix and verified that the issue does not reproduce. The fix is live in production as well.

As always, @ghuntley please reopen this issue if you still face the same problem!
