### ISSUE TITLE
Panic in versioncheck.go

### ISSUE THREAD

**Issue by gmichelo** [namespacelabs/foundation#953]
After I installed `namespace`, most invocations of `ns` besides `ns help` crash with the following trace:

```
❯ ns
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10204d783]

goroutine 70 [running]:
namespacelabs.dev/foundation/internal/cli/fncobra.checkRemoteStatus({0x103468c18, 0xc001009dd0}, 0xc0005a52c0)
	namespacelabs.dev/foundation/internal/cli/fncobra/versioncheck.go:55 +0x283
created by namespacelabs.dev/foundation/internal/cli/fncobra.DoMain.func1
	namespacelabs.dev/foundation/internal/cli/fncobra/main.go:168 +0x3a5
```

I suspect my network is blocking the URL the `ns` is trying to connect to. 

I noticed that the installation script installs an older version (v0.0.73). This panic does not occur with tip of main branch.

https://github.com/namespacelabs/foundation/blob/84eb04f9f1c1bffa9dd5ae2a0bcf12695a3ea7b4/install/install.sh#L8

Can we upgrade the default version to a more recent one?

**Comment by gmichelo** [comment]
BTW, I also noticed that maybe here we should return early?

https://github.com/namespacelabs/foundation/blob/v0.0.73/internal/cli/fncobra/versioncheck.go#L52

**Comment by nichtverstehen** [comment]
Thanks for the report. Yes, we needed an early return there :).

**Comment by n-g** [comment]
@nichtverstehen do I understand correctly that the version in the script refers to nsboot?

Merging ns and nsboot would resolve this source of confusion then.
