### ISSUE TITLE
feature: add ability to create new environments with `prepare`

### ISSUE THREAD

**Issue by hugosantos** [namespacelabs/foundation#974]
If no environments are specified, `ns` assumes the existence of `dev`, `staging` and `prod`.

This setup is fairly team specific, so we should make it trivial to create new environments instead.

Something like:

```
ns prepare local --env=foobar --create-env --env_purpose=DEVELOPMENT
```

Or alternatively,

```
ns workspace create-env --name=foobar --purpose=DEVELOPMENT
```

Where purpose is one of DEVELOPMENT, TESTING or PRODUCTION. For now lets assume that runtime is always kubernetes, so we don't need to ask users about it.

It would be practical to generate environments inline in `prepare`, as we usually do both environment creation and setup in tandem. But open for ideas here.

Environments need to be declared, and they live under `environment` in `ns-workspace.cue`. E.g.

```
environment: {
	dev: {
		runtime: "kubernetes"
		purpose: "DEVELOPMENT"
	}
	staging: {
		runtime: "kubernetes"
		purpose: "PRODUCTION"
	}
}
```

In order to mutate this block, the `EditableWorkspaceData` instead will need to be augmented to set environments.

https://github.com/namespacelabs/foundation/blob/36b0f02a591d765c068ea7f16def14e2926132d7/std/pkggraph/workspacedata.go#L14-L20

The Cue workspace loader will need to be updated to allow setting workspaces. This is a bit gnarly, but there's some existing code that should guide the way:

https://github.com/namespacelabs/foundation/blob/36b0f02a591d765c068ea7f16def14e2926132d7/internal/frontend/cuefrontend/module.go#L227-L228

**Comment by n-g** [comment]
https://github.com/namespacelabs/foundation/pull/975
