### ISSUE TITLE
[PUB-15] rename "intent" to "input" in resources?

### ISSUE THREAD

**Issue by hugosantos** [namespacelabs/foundation#985]
May be more understandable.

E.g.

https://github.com/namespacelabs/examples/blob/main/multitier/03-withresources/apibackend/server.cue#L28-L31

@nicolasalt @n-g @nichtverstehen @szferi for thoughts.

<sub>[PUB-15](https://linear.app/namespacelabs/issue/PUB-15/rename-intent-to-input-in-resources)</sub>

**Comment by n-g** [comment]
Resource providers have two ways of depending on other resources. In-line (called resources) and provided externally (called inputs).

We should revisit the names of these fields in the same refactor.
