### ISSUE TITLE
[PUB-16] introduce a standard helm integration via resource providers

### ISSUE THREAD

**Issue by hugosantos** [namespacelabs/foundation#991]
There are many providers already packaged as helm charts, we should explore a standard integration that maps intent and helm values, to use existing helm charts.

<sub>[PUB-16](https://linear.app/namespacelabs/issue/PUB-16/introduce-a-standard-helm-integration-via-resource-providers)</sub>

**Comment by ADustyOldMuffin** [comment]
I think this is fairly important and would be interested in this. A workflow for many is to deploy existing things like redis, temporal, or most 3rd party tools as helm charts to save time.
